<?php

// Add more file type(s) other than `File::config['type']` here so that the editor will accept them

return [
    'application/octet-stream' => 1,
    'application/pdf' => 1,
    'application/php' => 1,
    'application/vnd.ms-fontobject' => 1,
    'application/x-httpd-php' => 1,
    // 'application/x-httpd-php-source' => 1,
    'application/x-tar' => 1,
    'application/x-7z-compressed' => 1,
    'application/zip' => 1,
	'audio/midi' => 1,
	'audio/mpeg' => 1,
	'audio/ogg' => 1,
	'audio/wav' => 1,
	'audio/x-matroska' => 1,
	'audio/x-ms-wax' => 1,
	'audio/x-ms-wma' => 1,
	'audio/x-realaudio' => 1,
    'font/otf' => 1,
	'font/ttf' => 1,
    'font/woff' => 1,
    'font/woff2' => 1,
    'image/bmp' => 1,
    'image/svg+xml' => 1,
    'image/tiff' => 1,
    'image/x-icon' => 1,
	'text/calendar' => 1,
	'text/csv' => 1,
    'text/php' => 1,
	'text/richtext' => 1,
	'text/tab-separated-values' => 1,
    'text/x-php' => 1,
	'video/avi' => 1,
	'video/divx' => 1,
	'video/mpeg' => 1,
	'video/mp4' => 1,
	'video/ogg' => 1,
	'video/quicktime' => 1,
	'video/webm' => 1,
	'video/x-flv' => 1,
	'video/x-matroska' => 1,
	'video/x-ms-asf' => 1,
	'video/x-ms-wm' => 1,
	'video/x-ms-wmv' => 1,
	'video/x-ms-wmx' => 1
];