<?php

// Add more file extension(s) other than `File::config['x']` here so that the editor will accept them

return [
    // 'apng' => 1,
	'asc' => 1,
	'asf' => 1,
    'asx' => 1,
	'avi' => 1,
    'bmp' => 1,
    'c' => 1,
    'cc' => 1,
	'csv' => 1,
	'divx' => 1,
    'eot' => 1,
	'flv' => 1,
    'h' => 1,
    'htaccess' => 1,
    'ico' => 1,
	'ics' => 1,
	'mid' => 1,
    'midi' => 1,
	'mka' => 1,
	'mkv' => 1,
	'mov' => 1,
    'mpe' => 1,
	'mpeg' => 1,
    'mpg' => 1,
	'mp3' => 1,
	'mp4' => 1,
    'm4a' => 1,
    'm4b' => 1,
    'm4v' => 1,
    'oga' => 1,
	'ogg' => 1,
	'ogv' => 1,
    'otf' => 1,
    'pdf' => 1,
    'php' => 1,
    // 'phps' => 1,
    'qt' => 1,
	'ra' => 1,
    'ram' => 1,
	'rtx' => 1,
    'svg' => 1,
    'tar' => 1,
    'tif' => 1,
    'tiff' => 1,
	'tsv' => 1,
    'ttf' => 1,
	'wav' => 1,
	'wax' => 1,
	'webm' => 1,
	'wm' => 1,
	'wma' => 1,
	'wmv' => 1,
	'wmx' => 1,
    'woff' => 1,
    'woff2' => 1,
    'zip' => 1,
    '7z' => 1
];