<?php

if ($user['status'] !== 1 || $_['task'] !== 'g') {
    if (Is::user()) {
        Alert::error(i('Permission denied for your current user status: %s', '<code>' . $user['status'] . '</code>') . '<br><small>' . $url->current . '</small>');
        Guard::kick($url . $_['/'] . '::g::' . $_['state']['path'] . '/1' . $url->query('&', ['content' => false, 'tab' => false]) . $url->hash);
    } else {
        Guard::kick("");
    }
}

$GLOBALS['_']['content'] = $_['content'] = 'state';

Route::set($_['/'] . '\:\:g\:\:/.state', 200, function($lot, $type) {
    extract($GLOBALS, EXTR_SKIP);
    if (isset($_['i'])) {
        // Force as item page
        Guard::kick($url->clean . $url->query . $url->hash);
    }
    $panes = $paths = $skins = [];
    foreach (glob(LOT . DS . '*', GLOB_NOSORT | GLOB_ONLYDIR) as $panel) {
        $n = basename($panel);
        if (strpos('_.-', $n[0]) !== false) {
            continue;
        }
        $panes['/' . $n] = $n === 'x' ? 'Extension' : ucfirst($n);
    }
    foreach (glob(PAGE . DS . '*.{page,archive}', GLOB_NOSORT | GLOB_BRACE) as $path) {
        $paths['/' . pathinfo($path, PATHINFO_FILENAME)] = S . (new Page($path))->title . S;
    }
    foreach (glob(CONTENT . DS . '*' . DS . 'about.page', GLOB_NOSORT) as $skin) {
        $skins[basename(dirname($skin))] = S . (new Page($skin))->title . S;
    }
    asort($panes);
    asort($paths);
    asort($skins);
    $zones = Cache::hit(__FILE__, function() {
        $zones = [];
        $regions = [
            \DateTimeZone::AFRICA,
            \DateTimeZone::AMERICA,
            \DateTimeZone::ANTARCTICA,
            \DateTimeZone::ASIA,
            \DateTimeZone::ATLANTIC,
            \DateTimeZone::AUSTRALIA,
            \DateTimeZone::EUROPE,
            \DateTimeZone::INDIAN,
            \DateTimeZone::PACIFIC,
        ];
        $timezones = [];
        $timezone_offsets = [];
        foreach ($regions as $region) {
            $timezones = array_merge($timezones, \DateTimeZone::listIdentifiers($region));
        }
        foreach ($timezones as $timezone) {
            $tz = new \DateTimeZone($timezone);
            $timezone_offsets[$timezone] = $tz->getOffset(new \DateTime);
        }
        asort($timezone_offsets);
        foreach ($timezone_offsets as $zone => $offset) {
            $offset_prefix = $offset < 0 ? '-' : '+';
            $offset_formatted = gmdate('H:i', abs($offset));
            $zones[$zone] = 'GMT' . $offset_prefix . $offset_formatted . ' (' . strtr($zone, '_', ' ') . ')';
        }
        return $zones;
    }, '1 year');
    $GLOBALS['_']['lot'] = array_replace_recursive(require __DIR__ . DS . '..' . DS . 'state' . DS . 'state.php', $_['lot']);
    $GLOBALS['_']['lot']['bar']['lot'][0]['lot']['folder']['url'] = $url . $_['/'] . '::g::' . $_['state']['path'] . '/1' . $url->query('&', ['content' => false, 'tab' => false]) . $url->hash;
    $GLOBALS['_']['lot']['bar']['lot'][0]['lot']['s']['hidden'] = true;
    $GLOBALS['_']['lot']['desk']['lot']['form']['lot'][1]['lot']['tabs']['lot'] = array_replace_recursive([
        'file' => [
            'icon' => 'M10,20V14H14V20H19V12H22L12,3L2,12H5V20H10Z',
            'title' => false,
            'description' => 'Site',
            'name' => 'site',
            'lot' => [
                'fields' => [
                    // type: Fields
                    'lot' => [
                        '0' => [
                            'type' => 'Hidden',
                            'name' => 'path',
                            'value' => '/../state.php'
                        ],
                        '1' => [
                            'type' => 'Hidden',
                            'name' => 'file[name]',
                            // No use. This field was added just to remove error message of
                            // empty `file[name]` field generated by `_\lot\x\panel\task\get\file()`
                            'value' => 'state.php'
                        ],
                        'content' => ['hidden'=> true],
                        'name' => ['hidden' => true],
                        'title' => [
                            'type' => 'Text',
                            'name' => 'state[title]',
                            'alt' => $state->title ?? 'Title Goes Here',
                            'value' => $state->title,
                            'width' => true,
                            'stack' => 10
                        ],
                        'description' => [
                            'type' => 'Content',
                            'name' => 'state[description]',
                            'alt' => 'Description goes here...',
                            'value' => $state->description,
                            'width' => true,
                            'stack' => 20
                        ],
                        'skin' => [
                            'type' => 'Combo',
                            'name' => 'state[name]',
                            'value' => $state->name,
                            'lot' => $skins,
                            'stack' => 30
                        ],
                        'path' => [
                            'title' => 'Home',
                            'type' => 'Combo',
                            'name' => 'state[path]',
                            'value' => $state->path,
                            'lot' => $paths,
                            'stack' => 40
                        ]
                    ]
                ]
            ]
        ],
        'panel' => [
            'lot' => [
                'fields' => [
                    'type' => 'Fields',
                    'lot' => [
                        'path' => [
                            'title' => 'Home',
                            'description' => 'Choose default page that will open after logged-in.',
                            'type' => 'Combo',
                            'name' => 'state[x][panel][path]',
                            'value' => $state->x->panel->path ?? null,
                            'lot' => $panes,
                            'stack' => 10
                        ]
                    ],
                    'stack' => 10
                ]
            ],
            'stack' => 20
        ],
        'locale' => [
            'lot' => [
                'fields' => [
                    'type' => 'Fields',
                    'lot' => [
                        'zone' => [
                            'type' => 'Combo',
                            'name' => 'state[zone]',
                            'value' => $state->zone,
                            'lot' => $zones,
                            'width' => true,
                            'stack' => 10
                        ],
                        'direction' => [
                            'type' => 'Item',
                            'name' => 'state[direction]',
                            'value' => $state->direction,
                            'lot' => [
                                'ltr' => '<abbr title="Left to Right">LTR</abbr>',
                                'rtl' => '<abbr title="Right to Left">RTL</abbr>'
                            ],
                            'stack' => 20
                        ],
                        'charset' => [
                            'type' => 'Text',
                            'name' => 'state[charset]',
                            'alt' => ($v = $site->charset) ?? 'utf-8',
                            'value' => $v,
                            'stack' => 30
                        ],
                        'language' => [
                            'description' => 'This value does not determine the I18N system on your site unless you want to make an I18N extension that depends on this value.',
                            'type' => 'Text',
                            'name' => 'state[language]',
                            'alt' => ($v = $site->language) ?? 'en',
                            'value' => $v,
                            'stack' => 40
                        ]
                    ],
                    'stack' => 10
                ]
            ],
            'stack' => 30
        ]
    ], $GLOBALS['_']['lot']['desk']['lot']['form']['lot'][1]['lot']['tabs']['lot'] ?? []);
    $GLOBALS['_']['lot']['desk']['lot']['form']['lot'][2]['lot']['fields']['lot'][0]['lot']['tasks']['lot']['s']['description'] = ['Save to %s', ".\\state.php"];
    $GLOBALS['_']['lot']['bar']['lot'][0]['lot']['search']['hidden'] = true; // Hide search form
    $GLOBALS['_']['lot']['desk']['lot']['form']['lot'][2]['lot']['fields']['lot'][0]['lot']['tasks']['lot']['l']['hidden'] = true; // Hide delete button
    $GLOBALS['t'][] = i('Panel');
    $GLOBALS['t'][] = i('State');
    State::set([
        'has' => [
            'parent' => count($_['chop']) > 1,
        ],
        'is' => [
            'error' => false,
            'page' => true,
            'pages' => false
        ]
    ]);
    $this->content(__DIR__ . DS . '..' . DS . 'content' . DS . 'panel.php');
}, 10);